"""
Build gallery/README.md, the gallery index, from each item's README front matter.

    uv run python scripts/build_gallery.py          # write the index
    uv run python scripts/build_gallery.py --check  # fail if it's out of date (CI)

An item is a folder gallery/<slug>/ whose README.md starts with:

    ---
    title: Where players die on Mirage
    author: PureSkill.gg
    official: true
    data: 3,742 deaths in 60 matches, July 2026
    image: mirage-deaths.png
    video: https://www.youtube.com/watch?v=...   (optional)
    ---
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GALLERY = ROOT / "gallery"
REQUIRED = ("title", "author", "official", "data", "image")
HEADER = """# Gallery

Graphics made with this repo. Each folder holds the notebook or script that made
the graphic, the images, and a README with the story behind it.

To add one, copy `templates/gallery-item/` to `gallery/<your-slug>/`, make your
graphic, then run `uv run python scripts/build_gallery.py`. See
[CONTRIBUTING.md](../CONTRIBUTING.md).

<!-- Generated by scripts/build_gallery.py from each item's README. Don't edit below by hand. -->
"""


def front_matter(path):
    """The key: value pairs between the leading --- lines of a Markdown file."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    meta = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return meta
        key, sep, value = line.partition(":")
        if sep:
            meta[key.strip()] = value.strip()
    return {}


def items(gallery=GALLERY):
    """(slug, meta, problems) for every item folder, sorted by slug."""
    out = []
    for folder in sorted(p for p in gallery.iterdir() if p.is_dir() and not p.name.startswith((".", "_"))):
        readme = folder / "README.md"
        meta = front_matter(readme) if readme.is_file() else {}
        problems = [f"missing '{k}' in README front matter" for k in REQUIRED if not meta.get(k)]
        if meta.get("official") not in (None, "", "true", "false"):
            problems.append("'official' must be true or false")
        if meta.get("image") and not (folder / meta["image"]).is_file():
            problems.append(f"image {meta['image']} not found")
        out.append((folder.name, meta, problems))
    return out


def render(entries):
    """The index Markdown for the given items."""
    lines = [HEADER]
    if not entries:
        lines.append("\nNothing here yet. Be the first.\n")
        return "\n".join(lines)
    for slug, meta, _ in entries:
        kind = "Official" if meta["official"] == "true" else "Community"
        lines.append(f"\n## [{meta['title']}]({slug}/)\n")
        lines.append(
            f'<a href="{slug}/"><img src="{slug}/{meta["image"]}" width="480" alt="{meta["title"]}"></a>\n'
        )
        byline = f"{kind} · by {meta['author']} · {meta['data']}"
        if meta.get("video"):
            byline += f" · [video]({meta['video']})"
        lines.append(byline + "\n")
    return "\n".join(lines)


def main(argv=None):
    """Command-line entry point."""
    parser = argparse.ArgumentParser(description="Build gallery/README.md.")
    parser.add_argument("--check", action="store_true", help="fail if the index is out of date")
    args = parser.parse_args(argv)
    entries = items()
    problems = [f"gallery/{slug}: {p}" for slug, _, ps in entries for p in ps]
    if problems:
        print("\n".join(problems))
        return 1
    text = render(entries)
    index = GALLERY / "README.md"
    if args.check:
        current = index.read_text(encoding="utf-8") if index.is_file() else ""
        if current.replace("\r\n", "\n") != text:
            print("gallery/README.md is out of date; run: uv run python scripts/build_gallery.py")
            return 1
        return 0
    index.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {index.relative_to(ROOT)} ({len(entries)} items)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
